Updates to RTL services
picons/picons pull request #2263
Opened 2024-07-03 08:07 UTC by SmoothMC

Optimize RTL Germany Service Logos
Rename RTL Service Super RTL to RTL Super in srp and snp (New Name since 07.2023)
Remove unused Super RTL Logos

2024-07-03 23:20 UTC, Lexzie requested changes
I can imagine to prefer a stacked logo, but what is the reason for the colouring?
I checked RTL Super and the colours we have are also used on the website, so what's wrong about that?

2024-07-03 23:24 UTC, Lexzie commented on build-source/logos/rtl.default.svg
These colours are indeed correct when checking on their website, https://www.rtl.de/

2024-07-04 07:38 UTC, SmoothMC commented
Hey Lexzie,

for now i used the colors from the rtl+ website live tv here
[https://plus.rtl.de/video-tv/live-tv/rtl-1](https://plus.rtl.de/video-tv/live-tv/rtl-1)

But rtl keeps changing the colors for each show or tv-formats like news etc.

2024-07-04 16:21 UTC, Lexzie commented
> Hey Lexzie,
> 
> for now i used the colors from the rtl+ website live tv here https://plus.rtl.de/video-tv/live-tv/rtl-1
> 
> But rtl keeps changing the colors for each show or tv-formats like news etc.

That's what I am saying.
Let's keep the colours as they are.
But I am okay with making the logos stacked.

2024-07-04 17:39 UTC, SmoothMC commented
Hm ok...I have a look on it.
Even though I like the colors that I picked from rtl+ 😝

2024-07-05 10:16 UTC, SmoothMC commented
Hey Lexzie,

i update the colors again. i hope we now ready to merge. ;)

2024-07-06 19:31 UTC, SmoothMC reviewed
Update Logo Colors to Website Referenz

2024-07-06 19:43 UTC, SmoothMC reviewed
Update Logo Colors to Website Referenz

2024-07-06 22:57 UTC, AbuBaniaz commented
@Lexzie 
Is this okay to merge?

2024-07-07 07:37 UTC, SmoothMC commented
Yes! ;)

2024-07-08 19:15 UTC, SmoothMC commented
@Lexzie do I miss something? Or why we don't merge?

2024-07-08 19:17 UTC, TheLegoBatman commented
He most likely doesn't get notified of the tagging of his username.

2024-07-08 19:17 UTC, merged

2024-07-09 21:06 UTC, Lexzie commented
> He most likely doesn't get notified of the tagging of his username.

I was, but had too much other things to do.